import "@/styles/index.css";

export const metadata = {
  title: 'Sign In | Blog Dashboard',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="auth">{children}</body>
    </html>
  )
}
