import "@/sass/blog/main.scss";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "@/components/blog/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Blog Website",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className + " blog"}>
				<div className="container blog">
					<Header />
					{children}
				</div>
			</body>
		</html>
	);
}
