import "@/sass/blog/main.scss";

import type { Metadata } from "next";
import { Header } from "@/components/blog/Header";
import { GoToTopButton } from "@/components/common";
import ThemeContext from "@/contexts/ThemeContext";
import { Footer } from "@/components/blog/Footer";

export const metadata: Metadata = {
	title: "Blog Website",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<ThemeContext>
					<div className="blog">
						<Header />
						{children}
						<GoToTopButton />
					</div>
					<Footer />
				</ThemeContext>
			</body>
		</html>
	);
}
