import type { Metadata } from "next";
import { Header } from "@/components/dashboard/Header";

import "@/styles/index.css";
import { SideMenu } from "@/components/dashboard/SideMenu";
import { Locator } from "@/components/dashboard/Locator";

export const metadata: Metadata = {
	title: "Blog Dashboard",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="dashboard">
				<div className="container dashboard">
					<SideMenu />
					<div className="dashboard__main">
						<Header />
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
