import "@/styles/index.css";

import { Header } from "@/components/dashboard/Header";
import { SideMenu } from "@/components/dashboard/SideMenu";
import { SessionProvider } from "next-auth/react";
import Authenticate from "@/components/auth/Authenticate";

import type { Metadata } from "next";
export const metadata: Metadata = {
	title: "Blog Dashboard",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="dashboard">
				<Authenticate>
					<SessionProvider>
						<div className="container dashboard">
							<SideMenu />
							<div className="dashboard__main">
								<Header />
								{children}
							</div>
						</div>
					</SessionProvider>
				</Authenticate>
			</body>
		</html>
	);
}
